### ISSUE TITLE
Button Position when Enabled

### ISSUE THREAD

**Issue by Xorag** [Vampyr7878/GarrisonOrderHallReport#1]
As a follow-up to my curse comment I've noticed the following:

When the addon is disabled my button is here:
![image](https://github.com/Vampyr7878/GarrisonOrderHallReport/assets/42698965/4d7ca4ac-e5bd-4422-937b-4e87e9b2bac1)

When the addon is enabled however:
![image](https://github.com/Vampyr7878/GarrisonOrderHallReport/assets/42698965/4ea251b2-daa9-4ba8-afdd-0cbdf273f83c)

No other addons enabled while testing/showing this as well. The only reason I've noticed is that I've positioned a couple other minimap buttons relative to the big button.

**Comment by Vampyr7878** [comment]
I see now. I know what could cuase it. I will fix it,
