### ISSUE TITLE
Issues with garrison Button Layout

### ISSUE THREAD

**Issue by millanzarreta** [Vampyr7878/GarrisonOrderHallReport#3]
Hi. Two issues with the garrison button.

---

The first one is that the garrison Button Size can be incorrect when swapping 'Report Type' from the addon options. I have done several tests and normally switching between different styles of garrison buttons does not cause a problem, except for the following:
- From 'BFA' to 'Draenor'
- From 'SL' to 'Draenor'
- From 'BFA' to 'Legion'
- From 'SL' to 'Legion'

Some pictures:
- Draenor normal correct layout:
![draenor_normal](https://github.com/user-attachments/assets/92b2633d-b01a-4c7a-a35e-835a78bf3ed9)

- Draenor from BFA incorrect layout:
![draenor_from_bfa](https://github.com/user-attachments/assets/b76323e9-c7d8-4643-a445-8d9d25847e86)

- Draenor from SL incorrect layout:
![draenor_from_sl](https://github.com/user-attachments/assets/6b9c38d4-8f94-4942-8d06-ea3ae53ab715)

- Legion normal correct layout:
![legion_normal](https://github.com/user-attachments/assets/1b3c0f20-0ae1-4c71-abb6-5e7c63d60414)

- Legion from BFA incorrect layout:
![legion_from_bfa](https://github.com/user-attachments/assets/493619b2-e55d-4837-ba9d-d6aeed4bb823)

- Legion from SL incorrect layout:
![legion_from_sl](https://github.com/user-attachments/assets/6dbf1daa-44ce-486c-92dc-09a2ed4cc5e7)

In these test cases, my SL covenant was night fae, but I assume that these aforementioned "From 'SL' ..." errors will also occur with other SL covenants.

It is a minor bug since it only occurs when changing the type of garrison button in the addon options, not when logging in.

EDIT: Doing more checking it seems that the problem always occurs when setting the button types to 'Draenor' or 'Legion', which do not update their size. Differences are only reported when swapping from 'SL' or 'BFA' because the size of these does not match. Seems that 'Dragonflight' or 'KhazAlgar' have the same size as 'Draenor' and 'Legion' (53x53), and that is why this problem does not occur for these cases. It seems like the solution would be to simply make sure you set the correct size when changing the button type to 'Draenor' or 'Legion'.

---

The second issue with the garrison Button is the Highlighting overlay when you mouse over it. It seems that this is only set for the Dragonflight, BFA, and SL buttons. For the Draenor, Legion and KhazAlgar buttons, their corresponding highlighting is not established, leaving the highlighting from the previous button type.

This is a problem not only when the button type is changed from the addon options, but also when the button is loaded by default when when logging in if its button type is Draenor, Legion or KhazAlgar. In this case, the previous highlight will remain, which is currently in the pre-patch the Dragonflight one.

---

Regards.

**Comment by Vampyr7878** [comment]
Thanks for this detailed report on the issue. I'll take a look and see what can I do about it.

**Comment by Vampyr7878** [comment]
I got the code that sets up the buttons directly from Blizzard UI code, it seems they didn't worry about this kind of issues there. Size and proportions of the buttons should be fine. As for highlights, Blizzard code doesn't set up any for Garrison and Order Hall so I had to do a bit of a hack.
